# Extension configuration
name = "urgify-theme"
uid = "2dbfabeb-4098-6bca-cd1c-346f07018b9e643e0b97"
type = "theme_app_extension"

# Assets to be bundled and served
[[assets]]
source = "assets/urgify.js"
destination = "assets/urgify.js"

[[assets]]
source = "assets/urgify.min.css"
destination = "assets/urgify.min.css"

[[assets]]
source = "assets/urgify-stock-alert.js"
destination = "assets/urgify-stock-alert.js"

[[assets]]
source = "assets/urgify-stock-alert.css"
destination = "assets/urgify-stock-alert.css"

[[assets]]
source = "assets/urgify-popup.js"
destination = "assets/urgify-popup.js"

[[assets]]
source = "assets/urgify-popup.css"
destination = "assets/urgify-popup.css"

# Blocks definition
[[blocks]]
type = "liquid"
name = "Urgify – Countdown"
source = "blocks/countdown.liquid"

[[blocks]]
type = "liquid"
name = "Urgify – Limited Offer"
source = "blocks/limited-offer.liquid"

[[blocks]]
type = "liquid"
name = "Urgify – Scarcity Banner"
source = "blocks/scarcity-banner.liquid"

[[blocks]]
type = "liquid"
name = "Urgify – Core"
source = "blocks/app-embed.liquid"